/* OS TYPES,QUE SÃO AS ACTIONS TYPES,É RECOMENDADO SEPARAR NUM ARQUIVO PRÓPRIO
PARA IMPORTARMOS APENAS AS CONSTANTES
*/
 
export const CADASTRACLIENTES_PAGE_TITLE_VALUE =
  "CADASTRACLIENTES_PAGE_TITLE_VALUE";

export const CADASTRAIMOVEIS_PAGE_TITLE_VALUE =
  "CADASTRAIMOVEIS_PAGE_TITLE_VALUE";
