/* AQUI A FUNÇÃO É A ACTION CREATOR, E O QUE ELA RETORNA,QUE É O OBJETO, É A
  ACTION.AO SER DISPARADA, ELA COMUNICARÁ AO REDUCER QUE O TYPE É CADASTRACLIENTES_PAGE_TITLE_VALUE,
  ALÉM DO VALOR NEWVALUE: VALUE QUE DEVERÁ SER ATUALIZADO NA STORE.NOVAMENTE AQUI,CASO PREFIRA USAR O 
  MESMO NOME PARA CHAVE E VALOR, FICA A ESCOLHA DO DEV.
*/

import { CADASTRACLIENTES_PAGE_TITLE_VALUE } from "./actionTypes";
import { CADASTRAIMOVEIS_PAGE_TITLE_VALUE } from "./actionTypes";

export const changeCadastraClientesTitle = value => ({
  type: CADASTRACLIENTES_PAGE_TITLE_VALUE,
  newValue: value
});

export const changeCadastraImoveisTitle = value => ({
  type: CADASTRAIMOVEIS_PAGE_TITLE_VALUE,
  newValue: value
});
